var dd = {
	content: [
		{
			style: 'tableExample',
			table: {
				widths: ['*', 1, '*', 1, '*', 1, '*', 1, '*', 1, '*', 1, '*', 1, '*', 1, '*', 1, '*'],
				heights: [18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4, 18, 4],
				body: [
					[
					    {
					        text: 'data1',
					       // rowSpan: 1,
                            // colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data2', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					],
					[
					    { text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: '', fillColor: 'gray'}
					],
					[
					    {
					        text: 'data1',
					        rowSpan: 1,
                            colSpan: 1,
                            //border: [true, true, true, true],
					    }, 
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data3', color: 'gray'},
					    {text: '', fillColor: 'gray'}, 
					    {text: 'data4', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data5', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data6', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data7', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data9', color: 'gray'},
					    {text: '', fillColor: 'gray'},
					    {text: 'data10', color: 'gray'}
					]
				],
			},
			layout: 'noBorders',
		}
	],
	styles: {
		tableExample: {
			margin: [-12, -9, -12, -12]
		}
	},
}